version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "12300:3306"
    environment:
      MYSQL_DATABASE: attendance
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    build: .
    container_name: my-backend-container
    ports:
      - "12310:3000"
    depends_on:
      - db