version: '3'

services:
  db:
    image: mysql:8.0
    container_name: eco-db-container
    ports:
      - "8922:3306"
    environment:
      MYSQL_DATABASE: eco
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    build: .
    container_name: eco-backend-container
    ports:
      - "8932:8932"
    depends_on:
      - db